import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createReaderStore} from '../assets/reader-state.js';
let failWrites=true,failAccess=false,failures=0;
const backing=new Map([['saved','[{"path":"blog/old/"}]']]);
const storage={getItem:key=>backing.get(key)??null,setItem:(key,value)=>{if(failWrites)throw new Error('QuotaExceededError');backing.set(key,value);}};
const store=createReaderStore(()=>{if(failAccess)throw new Error('SecurityError');return storage;},()=>failures++);
assert.equal(store.read('saved')[0].path,'blog/old/');
assert.equal(store.write('saved',[{path:'topics/budget/'}]),false);
assert.deepEqual(store.read('saved'),[{path:'topics/budget/'}],'A failed write must not revert to the old readable value');
assert.equal(backing.get('saved'),'[{"path":"blog/old/"}]');
assert.equal(store.write('saved',[]),false);assert.deepEqual(store.read('saved'),[],'Cancelling in fallback state remains effective');
failWrites=false;assert.equal(store.write('saved',[{path:'topics/annual/'}]),true);assert.equal(store.read('saved')[0].path,'topics/annual/');
failAccess=true;assert.deepEqual(store.read('unknown'),[]);assert.equal(store.write('saved',[{path:'topics/payg/'}]),false);assert.equal(store.read('saved')[0].path,'topics/payg/');
failAccess=false;backing.set('saved','[{"path":"brands/dalaocloud/"}]');store.invalidate('saved');assert.equal(store.read('saved')[0].path,'brands/dalaocloud/','Remote storage updates replace fallback state');
backing.set('saved','not-json');assert.deepEqual(store.read('saved'),[]);backing.set('saved','{"wrong":"shape"}');assert.deepEqual(store.read('saved'),[]);
assert.equal(failures,3);
const root=new URL('../',import.meta.url),html=fs.readFileSync(new URL('dist/topics/budget/index.html',root),'utf8');
assert(html.includes('data-save="topics/budget/"'));assert(html.includes('data-copy-url'));assert(html.includes('data-print'));
assert(fs.readFileSync(new URL('.github/workflows/pages.yml',root),'utf8').includes('npm run check'));
const report={status:'passed',quotaFailureFallback:true,deniedStorageFallback:true,fallbackCancellation:true,crossTabInvalidation:true,corruptRecordHandling:true,topicSaveCopyPrint:true,workflowRunsAllChecks:true};
fs.writeFileSync(new URL('READER-VALIDATION.json',root),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
