import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {articles,topics} from '../data/articles.mjs';
import {selectCandidates,quotaLabel,eligiblePlan,monthlyReferencePlan,unitPrice} from '../assets/metrics.js';
const root=path.resolve(import.meta.dirname,'..'),out=root+'/dist';
const brands=JSON.parse(fs.readFileSync(root+'/data/brands.json','utf8'));
const manifest=JSON.parse(fs.readFileSync(out+'/build-manifest.json','utf8'));
const expected=['breezenet','flycat','twilight','dalaocloud','worryfree','civet','flashleap','firefly','kuajie','flyv','laddercloud','wavenet','lingdong','invisible','stardream','lightspeed','v2yun','u1s1','jilian','globalcloud','guangnianti','sogo','yuzhou','2mao','1fly','edgenova','kosing','sujie','kuaili'];
assert.deepEqual(brands.map(b=>b.id),expected,'DalaoCloud fourth; other brands retain relative order');
assert.equal(articles.length,123);assert.equal(topics.length,24);assert.equal(brands.filter(b=>b.coupon).length,12);
assert.equal(new Set(articles.map(a=>a.id)).size,articles.length);assert.equal(new Set(articles.map(a=>a.title)).size,articles.length);
const titles=new Set(),descs=new Set();let links=0,fragments=0;
for(const file of manifest.pages){const full=path.join(out,file),html=fs.readFileSync(full,'utf8');const title=html.match(/<title>(.*?)<\/title>/s)?.[1];assert(title&& !titles.has(title),'Unique title: '+file);titles.add(title);assert.equal((html.match(/<h1[\s>]/g)||[]).length,1,'One h1: '+file);const desc=html.match(/<meta name="description" content="([^"]*)"/);assert(desc&&desc[1].length>=10,'Description: '+file);assert(!descs.has(desc[1]),'Unique description: '+file);descs.add(desc[1]);assert(html.includes('jichangnetwork.blog'),'Domain: '+file);assert(!html.includes('jichangblog.org'),'No old canonical: '+file);assert(!html.includes('云途集'),'No previous site name: '+file);assert(title.endsWith(' | 机场网络'),'New site name in title: '+file);assert(html.match(/<meta name="keywords" content="[^"\s][^"]+"/),'Page keywords: '+file);assert(html.includes('name="twitter:card"')&&html.includes('property="og:locale"'),'Social metadata: '+file);const canonical=html.match(/<link rel="canonical" href="([^"]+)"/)?.[1];assert.equal(canonical,'https://jichangnetwork.blog/'+(file==='index.html'?'':file.replace(/index\.html$/,'')),'Canonical: '+file);for(const j of html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)){const ld=JSON.parse(j[1]);assert(ld.some(x=>x['@type']==='Organization'&&x.name==='机场网络'),'Publisher identity: '+file);if(file.startsWith('blog/')&&file!=='blog/index.html')assert(ld.some(x=>x['@type']==='Article'&&x.datePublished&&x.publisher?.name==='机场网络'),'Article metadata: '+file);}
for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){const raw=m[1].replace(/&amp;/g,'&');if(/^(?:https?:|data:|mailto:)/.test(raw))continue;const url=new URL(raw,'https://local.test/'+file);let target=path.join(out,decodeURIComponent(url.pathname));if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');assert(fs.existsSync(target),`Broken local reference in ${file}: ${raw}`);links++;if(url.hash&&target.endsWith('.html')){const text=fs.readFileSync(target,'utf8');assert(text.includes(`id="${decodeURIComponent(url.hash.slice(1))}"`),`Missing anchor ${raw} in ${file}`);fragments++;}}
for(const a of html.matchAll(/<a[^>]+href="(https:\/\/[^\"]+aff[^\"]*)"[^>]*>/g))assert(a[0].includes('sponsored')&&a[0].includes('nofollow'),'Affiliate disclosure: '+file);
}
for(const a of articles){assert(a.sections.length>=3,'Substantive sections');assert(a.sections.reduce((n,s)=>n+s.paragraphs.join('').length,0)>=220,'Substantive article: '+a.id);assert(!a.title.includes('待补充'));}
const match=selectCandidates(brands,{budget:50,usage:150,multiplier:1,margin:20});assert.equal(match.required,180);assert(match.matches.length>0);assert(match.matches.every(x=>x.plan.price<=50&&x.plan.gb>=180));assert(match.matches.every(x=>!['firefly','jilian','kosing','flyv'].includes(x.brand.id)));assert.deepEqual(match.matches.map(x=>expected.indexOf(x.brand.id)),match.matches.map(x=>expected.indexOf(x.brand.id)).sort((a,b)=>a-b));assert.equal(selectCandidates(brands,{budget:1,usage:10000,multiplier:1,margin:0}).matches.length,0);assert.throws(()=>selectCandidates(brands,{budget:50,usage:-1,multiplier:1,margin:20}));
const yearly=brands.find(b=>b.id==='lingdong').plans.find(p=>p.quotaPeriod==='year-total');assert(quotaLabel(yearly).includes('年度总额'));assert(!eligiblePlan(brands.find(b=>b.id==='lingdong'),yearly));assert.equal(fs.readFileSync(out+'/CNAME','utf8').trim(),'jichangnetwork.blog');assert(!fs.existsSync(out+'/13962FC4C879EAC5F75353BE260788D1'));
const seo=JSON.parse(fs.readFileSync(out+'/seo-report.json','utf8'));
assert.equal(seo.site,'机场网络');assert.equal(seo.primaryKeyword,'机场推荐');assert.equal(seo.pageCount,manifest.pages.length);
const sitemapIndex=fs.readFileSync(out+'/sitemap.xml','utf8');assert(sitemapIndex.includes('<sitemapindex '));
const mapUrls=[];for(const item of seo.sitemaps){const file=new URL(item.url).pathname.slice(1);assert(sitemapIndex.includes(item.url));const xml=fs.readFileSync(out+'/'+file,'utf8');assert(xml.includes('<urlset '));const urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);assert.equal(urls.length,item.pages);mapUrls.push(...urls);}
assert.equal(new Set(mapUrls).size,mapUrls.length,'No duplicate sitemap URLs');assert.deepEqual([...mapUrls].sort(),seo.pages.filter(p=>p.indexable).map(p=>p.url).sort(),'Full canonical sitemap coverage');assert.equal(mapUrls.length,191);assert(seo.noindexPages.every(url=>!mapUrls.includes(url)));assert(fs.readFileSync(out+'/robots.txt','utf8').includes('Sitemap: https://jichangnetwork.blog/sitemap.xml'));assert(fs.readFileSync(out+'/feed.xml','utf8').includes('机场网络'));assert.equal((fs.readFileSync(out+'/feed.xml','utf8').match(/<item>/g)||[]).length,articles.length);
const dalao=brands.find(b=>b.id==='dalaocloud');assert.equal(dalao.url,'https://vip.dalaocloud.com/#/?code=Cp2sfYZg');assert.equal(dalao.coupon,'dly888');assert.equal(dalao.couponTerms.discount,.7);assert.equal(dalao.couponTerms.checkoutVerified,false);assert.equal(dalao.couponTerms.iosIdentifier,'dly');assert.equal(dalao.plans.length,6);assert.equal(brands.filter(b=>b.id!=='dalaocloud'&&b.coupon).length,11);
assert.deepEqual(dalao.plans.map(p=>[p.name,p.price,p.gb,p.cycle]),[['年付活动包',96,60,'年付'],['初云 · 入门版',23,null,'月付'],['凌云 · 基础版',43,300,'月付'],['御云 · 高级版',73,600,'月付'],['闲云 · 随心包',99,78,'一次性'],['悠云 · 长享包',199,160,'一次性']]);
assert.equal(monthlyReferencePlan(dalao).price,23);assert.deepEqual(dalao.plans[1].capacityValues,[130,120]);assert(!eligiblePlan(dalao,dalao.plans[1]));assert.equal(unitPrice(dalao.plans[1]),null);assert(!eligiblePlan(dalao,dalao.plans[0]));assert.equal(unitPrice(dalao.plans[0]),null);assert(quotaLabel(dalao.plans[0]).includes('30天'));assert.equal(dalao.plans[4].quotaPeriod,'total');assert.equal(dalao.plans[5].quotaPeriod,'total');assert(!eligiblePlan(dalao,dalao.plans[4]));
assert.equal(match.matches.find(x=>x.brand.id==='dalaocloud').plan.price,43);assert.equal(selectCandidates(brands,{budget:80,usage:400,multiplier:1,margin:0}).matches.find(x=>x.brand.id==='dalaocloud').plan.price,73);assert(!selectCandidates(brands,{budget:30,usage:100,multiplier:1,margin:0}).matches.some(x=>x.brand.id==='dalaocloud'));assert.equal(dalao.screenshots,undefined);assert.equal(dalao.ownerConfirmed,true);assert.equal(dalao.sourceType,'owner-provided');
const dalaoHtml=fs.readFileSync(out+'/brands/dalaocloud/index.html','utf8');assert(dalaoHtml.includes(dalao.url));assert(!/¥0(?:<| \/ 月)/.test(dalaoHtml),'No fake zero price');assert(dalaoHtml.includes('dly888')&&dalaoHtml.includes('新用户首次购买订阅套餐享7折'),'Coupon conditions visible');assert(dalaoHtml.includes('130 / 120 GB'),'Capacity conflict visible');assert(!fs.readFileSync(out+'/index.html','utf8').includes('¥0<'),'No fake price in homepage');assert(fs.readFileSync(out+'/index.html','utf8').includes('<h1>机场推荐，'));assert(dalaoHtml.includes('id="services"'));assert(!dalaoHtml.includes('<img')&&!dalaoHtml.includes('assets/evidence/')&&!dalaoHtml.includes('原始截图'),'No source photos displayed or linked');for(const plan of dalao.plans)for(const statement of plan.features)assert(dalaoHtml.includes(statement),'Service statement transcribed: '+statement);for(const name of ['dalaocloud-coupon.png','dalaocloud-annual-entry.png','dalaocloud-monthly.png','dalaocloud-payg.png'])assert(!fs.existsSync(out+'/assets/evidence/'+name),'No source photo in public site');
const humanMap=fs.readFileSync(out+'/sitemap/index.html','utf8');assert(humanMap.includes('工具与编辑说明'));for(const p of ['compare/','select/','research/','privacy/','disclosure/','methodology/'])assert(humanMap.includes('href="../'+p+'"'));
const report={status:'passed',site:'机场网络',primaryKeyword:'机场推荐',pages:manifest.pages.length,articles:articles.length,topics:topics.length,brands:brands.length,localReferences:links,anchors:fragments,brandOrder:'twilight third; dalaocloud fourth; worryfree fifth; original relative order preserved',coupons:12,dalaocloud:{planRecords:6,ownerConfirmed:true,presentation:'text-only',sourcePhotosPublished:0,serviceStatements:dalao.plans.reduce((n,p)=>n+p.features.length,0),coupon:'dly888',couponClaim:'new-user first subscription 30% off; checkout not performed by site',entryCapacityConflict:[130,120],monthlyReferencePrice:23},selector:{required:180,matches:match.matches.length,disputedExcluded:true,unknownQuotaExcluded:true,dalaocloudMonthlyPrice:43,conflictingEntryExcluded:true,annualAndPaygExcluded:true},metadata:'unique TDK; valid organization/article/breadcrumb JSON-LD; canonical; OG; Twitter',sitemaps:{index:true,submaps:4,indexedUrls:mapUrls.length,noindexExcluded:true},webmcp:'optional browser feature, UI validation recorded separately',bingSubmission:'not submitted; no verified production domain or site verification token'};
fs.writeFileSync(root+'/VALIDATION.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
