import {renderTopicDossier} from './topic-research.mjs';
import {dossiers} from '../data/topic-dossiers.mjs';
import {issue,topicIntros} from '../data/magazine-editorial.mjs';
export function magazineMark(){return '<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M9 29V11h5l12 18h5V11M9 11l22 18M14 11v18M26 11v18" stroke="currentColor" stroke-width="1.6"/><path d="M3 3h34v34H3z" stroke="currentColor" stroke-opacity=".4"/><path d="M3 12V3h9m16 34h9v-9" stroke="currentColor"/></svg>';}
function art(id){const diagram=id==='annual'?'<g transform="translate(165 105) rotate(-18)"><rect x="-73" y="-70" width="146" height="146" rx="9"/><rect x="-57" y="-53" width="114" height="114" rx="5" opacity=".35"/><path d="M-73-29H73M-38-78v22m76-22v22M-38 0h16m14 0H8m14 0h16M-38 25h16m14 0H8m14 0h16"/></g>':id==='budget'||id==='capacity'?'<path d="M59 164h209M81 164V99h35v65m33 0V63h35v101m32 0V30h35v134"/><path d="M66 69l55-29 48 11 77-39" opacity=".35"/><path d="M59 179h209M59 194h209" opacity=".15"/>':id==='payg'||id==='travel'?'<circle cx="165" cy="105" r="66"/><circle cx="165" cy="105" r="48" opacity=".25"/><path d="M165 39v66l38 24M88 105H60m210 0h-28M165 28V4m0 201v-24"/><path d="M80 24l-7 48 47-9" opacity=".3"/>':'<ellipse cx="165" cy="108" rx="99" ry="67" transform="rotate(-28 165 108)"/><ellipse cx="165" cy="108" rx="99" ry="39" transform="rotate(-28 165 108)" opacity=".35"/><ellipse cx="165" cy="108" rx="38" ry="67" transform="rotate(-28 165 108)"/><path d="M81 153l166-89M65 91l180 69" opacity=".35"/><circle cx="247" cy="64" r="4" fill="currentColor" stroke="none"/>';return `<svg class="edition-diagram" viewBox="0 0 330 220" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="1">${diagram}</g><path d="M20 24h26M20 24v26m264 146h20v-20" stroke="currentColor" stroke-opacity=".28"/></svg>`;}
function featureStory(a,ctx,i=0){const {E,articleUrl,readTime}=ctx;return `<article class="issue-story issue-story-${i}"><div class="issue-story-visual">${art(a.topic)}<span>${String(i+1).padStart(2,'0')} / ${E(ctx.label(a.topic))}</span></div><div class="issue-story-copy"><div class="story-category"><span>${E(ctx.label(a.topic))}</span><small>${a.kind==='guide'?'选购研究':'品牌解析'}</small></div><h3><a href="${articleUrl(a)}">${E(a.title)}</a></h3><p>${E(a.excerpt)}</p><div class="story-meta"><span>${readTime(a)}分钟阅读</span><a href="${articleUrl(a)}">阅读全文 <span aria-hidden="true">↗</span></a></div></div></article>`;}
export function renderMagazineHome(ctx){const {brands,articles,E,link,sectionTitle,brandRow}=ctx;const leads=issue.leadIds.map(id=>articles.find(a=>a.id===id));return `
<div class="magazine-issue-line"><span><i aria-hidden="true"></i>网络服务选购 · 专题与品牌研究</span><span>2026年10月 · 编辑精选</span></div>
<section class="magazine-hero"><img class="magazine-hero-art" src="${link('assets/network-editorial-hero.webp')}" width="1672" height="941" fetchpriority="high" decoding="async" alt=""><div class="magazine-hero-shade"></div><div class="magazine-hero-copy"><div class="hero-kicker"><span>JICHANG NETWORK</span><i></i><span>选购研究</span></div><h1>机场推荐，<br><em>读懂套餐再选择。</em></h1><p>价格、容量、付款周期与使用场景，<br>把影响选择的细节逐项讲清楚。</p><div class="hero-actions"><a class="button primary" href="#brands">浏览品牌图鉴 <span aria-hidden="true">↗</span></a><a class="button glass" href="${link('guide/')}">阅读选购指南</a></div><div class="hero-caption"><span></span>从真实需求出发，比较每一笔支出。</div></div><div class="hero-art-label"><small>THE ART OF CONNECTION</small><span>连接世界，理解选择。</span></div></section>
<div class="publication-strip"><div><strong>29</strong><span>品牌图鉴<small>套餐与付款方式</small></span></div><div><strong>123</strong><span>选购文章<small>方法、分析与场景</small></span></div><div><strong>24</strong><span>主题策划<small>围绕具体问题阅读</small></span></div><a href="${link('methodology/')}">资料有出处，计算有口径。<span>了解编辑方法 ↗</span></a></div>
<section class="decision-entry">${[['01','日常主力','按月用量，找到够用的容量。','monthly','月付选择'],['02','长期预算','一次付款，核对周期与权益。','annual','年付决策'],['03','低频备用','总额度，匹配不规律的使用。','payg','按量套餐']].map(([n,title,desc,id,label])=>`<a href="${link('topics/'+id+'/')}"><span>${n}</span><div><small>${label}</small><h2>${title}</h2><p>${desc}</p></div><i aria-hidden="true">↗</i></a>`).join('')}</section>
<section class="current-issue" id="current-issue"><div class="issue-heading"><div><div class="eyebrow">EDITOR’S SELECTION / 本期选题</div><h2>三种付款方式，<em>三套判断方法。</em></h2></div><p>日常主力看周期内的用量，年付看实际使用期限，按量包看额度消耗速度。四篇精选，理清套餐比较的起点。</p></div><div class="issue-stories">${leads.map((a,i)=>featureStory(a,ctx,i)).join('')}</div></section>
<section class="magazine-topics">${sectionTitle('THE COLLECTIONS / 专题策划','从一个问题，展开深入阅读','全部24个专题','topics/')}<div class="magazine-topic-covers">${[['budget','01','用量与成本','标称单价之外，算清真实支出。'],['annual','02','时间与预算','总付款、额度周期与实际使用月份。'],['evidence','03','资料与依据','身份、版本和未知字段，逐项核对。']].map(([id,n,title,deck])=>`<a class="magazine-topic-cover topic-cover-${id}" href="${link('topics/'+id+'/')}"><div><span>专题 ${n}</span><small>${E(ctx.label(id))}</small></div>${art(id)}<h3>${title}</h3><p>${deck}</p><span class="topic-cover-link">进入专题 <i aria-hidden="true">↗</i></span></a>`).join('')}</div></section>
<section class="magazine-brand-directory" id="brands">${sectionTitle('BRAND DIRECTORY / 品牌图鉴','品牌图鉴 · 29家','套餐并排对比','compare/')}<div class="directory-intro"><p>价格速览、容量周期、服务配置与优惠条件，集中整理在各品牌档案中。</p><small>29个品牌 · 沿用指定收录顺序</small></div><div class="catalog-toolbar"><label class="brand-filter"><span class="skip-label">查找品牌</span><input id="brand-query" type="search" placeholder="搜索品牌名称或英文名" aria-label="查找品牌，不改变收录顺序"></label><p class="result-count" id="brand-count" role="status" aria-live="polite">29个品牌 · 保持收录顺序</p></div><div class="brand-list">${brands.map((b,i)=>brandRow(b,i)).join('')}</div><p class="directory-source">参考金额及配置保留各自资料日期；当前售价与应付金额以品牌购买页为准。收录序号用于目录识别。</p></section>
<section class="editorial-closing"><div class="closing-monogram">${magazineMark()}</div><div><div class="eyebrow">RESEARCH & TOOLS / 选购工具</div><h2>把阅读，变成具体的选择。</h2><p>已确定预算和预计用量，可以筛选参考档位；<br>已有候选品牌，可以并排核对容量、周期和优惠。</p></div><div class="closing-actions"><a class="button primary" href="${link('select/')}">按预算选套餐 ↗</a><a class="button" href="${link('compare/')}">并排比较品牌 ↗</a></div></section>`;}
export function renderMagazineJournal(ctx){const {articles,topics,E,card,readTime}=ctx;const lead=articles.find(a=>a.id==='idle-quota-cost');return `<header class="page-intro magazine-page-intro"><div class="eyebrow">THE JOURNAL / 深度阅读</div><h1>方法、数字与场景，<br><em>让套餐比较有据可依。</em></h1><p>123篇选购文章，围绕预算、容量、付款周期与具体任务组织。按问题查找，按专题深入。</p></header><section class="journal-longread"><div class="journal-longread-art">${art('budget')}<span>本期重点 / 用量与成本</span></div><div><div class="eyebrow">FEATURED RESEARCH / 精选长文</div><h2><a href="${ctx.articleUrl(lead,1)}">${E(lead.title)}</a></h2><p>${E(lead.excerpt)}</p><div class="story-meta"><span>${readTime(lead)}分钟阅读 · 机场网络编辑组</span><a href="${ctx.articleUrl(lead,1)}">开始阅读 ↗</a></div></div></section><form class="toolbar" id="blog-filter"><div class="field wide"><label for="article-query">查找文章</label><input type="search" id="article-query" placeholder="品牌、付款方式或你关心的问题"></div><div class="field"><label for="article-topic">阅读专题</label><select id="article-topic"><option value="">全部专题</option>${topics.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select></div><div class="field"><label for="article-kind">内容类型</label><select id="article-kind"><option value="">全部内容</option><option value="guide">选购方法</option><option value="analysis">品牌研究</option></select></div></form><p class="result-count" id="article-count" role="status" aria-live="polite">共123篇文章</p><div class="cards" id="article-grid">${articles.map(a=>card(a,1)).join('')}</div><nav class="article-pagination" aria-label="文章分页" hidden><button class="button" id="previous-articles">← 上一页</button><span id="article-page" aria-live="polite"></span><button class="button" id="next-articles">下一页 →</button></nav><div class="empty" id="article-empty" hidden><h3>没有找到相关文章</h3><p>试试品牌名称或更简短的关键词，也可以切换专题。</p></div>`;}
export function renderMagazineTopics(ctx){const {topics,articles,articleTopicIds,E,link}=ctx;return `<header class="page-intro magazine-page-intro"><div class="eyebrow">THE COLLECTIONS / 专题策划</div><h1>按问题阅读，<br><em>从细节建立判断。</em></h1><p>24个独立研究专题，从预算计算到订阅维护。每个专题提供正文分析、比较表、情景案例和核对清单。</p></header><section class="topic-index-intro"><span>01—24</span><p>先读核心判断，再看比较与案例。<br>专题内附资料依据和三篇递进阅读。</p></section><div class="magazine-topics-index">${topics.map((t,i)=>{const count=articles.filter(a=>articleTopicIds(a).includes(t.id)).length;return `<article class="magazine-topic-index-card"><div class="topic-index-number">${String(i+1).padStart(2,'0')}</div><div><div class="eyebrow">${count}篇相关内容 / ${t.id.toUpperCase()}</div><h2><a href="${link('topics/'+t.id+'/',1)}">${E(t.name)}</a></h2><p>${E(dossiers[t.id].question)}</p><a class="text-arrow" href="${link('topics/'+t.id+'/',1)}">进入专题 ↗</a></div></article>`;}).join('')}</div>`;}
export function renderMagazineTopic(t,relevant,ctx){return renderTopicDossier(t,relevant,ctx,art(t.id));}
